# Generated by Django 2.2.7 on 2022-05-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ominicontacto_app', '0094_campana_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitioexterno',
            name='nombre',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
